-- Actualiza las listas de Zone y Sector (nuevas zonas/sectores + reordenamiento
-- alfabético) y migra los datos existentes de Business/SupportPost al nuevo
-- vocabulario. Mapeo acordado con el equipo (valor viejo -> valor nuevo):
--
-- Zone:   ESTACION -> LA_ESTACION | OTRA -> RURAL_ALEDANA | el resto igual
-- Sector: ALIMENTOS_Y_BEBIDAS -> ALIMENTOS_RESTAURANTES
--         ABARROTES_Y_TIENDA -> TIENDAS_VIVERES
--         ROPA_Y_CALZADO -> CONFECCION_COSTURA
--         BELLEZA_Y_CUIDADO_PERSONAL -> BELLEZA_CUIDADO
--         SALUD -> SALUD_BIENESTAR
--         EDUCACION -> EDUCACION_CLASES
--         TECNOLOGIA -> TECNOLOGIA_DIGITAL
--         CONSTRUCCION_Y_FERRETERIA -> FERRETERIA_CONSTRUCCION
--         TRANSPORTE -> TRANSPORTE_MENSAJERIA
--         SERVICIOS_PROFESIONALES -> OTRO
--         ARTE_Y_ARTESANIAS -> DISENO_ARTE
--         AGROPECUARIO -> JARDINERIA_AGRO
--         OTRO -> OTRO

-- ---------------------------------------------------------------------------
-- Zone
-- ---------------------------------------------------------------------------
CREATE TYPE "Zone_new" AS ENUM (
  'ATARDECERES',
  'CIUDADELA_DEL_NORTE',
  'CUMANDAY',
  'ECOTURISTICO_CERRO_DE_ORO',
  'LA_ESTACION',
  'LA_ESTRELLA',
  'LA_FUENTE',
  'LA_MACARENA',
  'NUEVO_HORIZONTE',
  'PALOGRANDE',
  'SAN_JOSE',
  'TESORITO',
  'UNIVERSITARIA',
  'RURAL_ALEDANA'
);

ALTER TABLE "Business" ALTER COLUMN "zone" TYPE "Zone_new" USING (
  CASE "zone"::text
    WHEN 'ESTACION' THEN 'LA_ESTACION'
    WHEN 'OTRA' THEN 'RURAL_ALEDANA'
    ELSE "zone"::text
  END
)::"Zone_new";

ALTER TABLE "SupportPost" ALTER COLUMN "zone" TYPE "Zone_new" USING (
  CASE "zone"::text
    WHEN 'ESTACION' THEN 'LA_ESTACION'
    WHEN 'OTRA' THEN 'RURAL_ALEDANA'
    ELSE "zone"::text
  END
)::"Zone_new";

DROP TYPE "Zone";
ALTER TYPE "Zone_new" RENAME TO "Zone";

-- ---------------------------------------------------------------------------
-- Sector
-- ---------------------------------------------------------------------------
CREATE TYPE "Sector_new" AS ENUM (
  'ALIMENTOS_RESTAURANTES',
  'BELLEZA_CUIDADO',
  'CONFECCION_COSTURA',
  'DISENO_ARTE',
  'EDUCACION_CLASES',
  'FERRETERIA_CONSTRUCCION',
  'HOGAR_ASEO',
  'JARDINERIA_AGRO',
  'MASCOTAS',
  'MECANICA_REPARACIONES',
  'SALUD_BIENESTAR',
  'TECNOLOGIA_DIGITAL',
  'TIENDAS_VIVERES',
  'TRANSPORTE_MENSAJERIA',
  'OTRO'
);

ALTER TABLE "Business" ALTER COLUMN "sector" TYPE "Sector_new" USING (
  CASE "sector"::text
    WHEN 'ALIMENTOS_Y_BEBIDAS' THEN 'ALIMENTOS_RESTAURANTES'
    WHEN 'ABARROTES_Y_TIENDA' THEN 'TIENDAS_VIVERES'
    WHEN 'ROPA_Y_CALZADO' THEN 'CONFECCION_COSTURA'
    WHEN 'BELLEZA_Y_CUIDADO_PERSONAL' THEN 'BELLEZA_CUIDADO'
    WHEN 'SALUD' THEN 'SALUD_BIENESTAR'
    WHEN 'EDUCACION' THEN 'EDUCACION_CLASES'
    WHEN 'TECNOLOGIA' THEN 'TECNOLOGIA_DIGITAL'
    WHEN 'CONSTRUCCION_Y_FERRETERIA' THEN 'FERRETERIA_CONSTRUCCION'
    WHEN 'TRANSPORTE' THEN 'TRANSPORTE_MENSAJERIA'
    WHEN 'SERVICIOS_PROFESIONALES' THEN 'OTRO'
    WHEN 'ARTE_Y_ARTESANIAS' THEN 'DISENO_ARTE'
    WHEN 'AGROPECUARIO' THEN 'JARDINERIA_AGRO'
    ELSE "sector"::text
  END
)::"Sector_new";

ALTER TABLE "SupportPost" ALTER COLUMN "sector" TYPE "Sector_new" USING (
  CASE "sector"::text
    WHEN 'ALIMENTOS_Y_BEBIDAS' THEN 'ALIMENTOS_RESTAURANTES'
    WHEN 'ABARROTES_Y_TIENDA' THEN 'TIENDAS_VIVERES'
    WHEN 'ROPA_Y_CALZADO' THEN 'CONFECCION_COSTURA'
    WHEN 'BELLEZA_Y_CUIDADO_PERSONAL' THEN 'BELLEZA_CUIDADO'
    WHEN 'SALUD' THEN 'SALUD_BIENESTAR'
    WHEN 'EDUCACION' THEN 'EDUCACION_CLASES'
    WHEN 'TECNOLOGIA' THEN 'TECNOLOGIA_DIGITAL'
    WHEN 'CONSTRUCCION_Y_FERRETERIA' THEN 'FERRETERIA_CONSTRUCCION'
    WHEN 'TRANSPORTE' THEN 'TRANSPORTE_MENSAJERIA'
    WHEN 'SERVICIOS_PROFESIONALES' THEN 'OTRO'
    WHEN 'ARTE_Y_ARTESANIAS' THEN 'DISENO_ARTE'
    WHEN 'AGROPECUARIO' THEN 'JARDINERIA_AGRO'
    ELSE "sector"::text
  END
)::"Sector_new";

DROP TYPE "Sector";
ALTER TYPE "Sector_new" RENAME TO "Sector";
